PTO_project/urls.py
# -*- coding: utf-8 -*-
"""PTO_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from PTO_project_core.views import test, VacationRequest, Dashboard, VacationSetStatus, Invitation, User, \
    SetUserVacation, oauth2callback, logout, export_user_vacations, ManagerSetUserVacation

admin.site.site_header = 'PTO administration'

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^login/$', LoginToPTO.as_view(), name='login'),

    url(r'^vacation_request/$', VacationRequest.as_view(), name='vacation_request'),
    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),
    url(r'^vacation_set_status/$', VacationSetStatus.as_view(), name='vacation_set_status'),
    url(r'^user/(\d+)/$', User.as_view(), name='user'),

    url(r'^set_user_vacation/(\d+)/$', SetUserVacation.as_view(), name='set_user_vacation'),

    url(r'^manager_set_user_vacation/(\d+)/$', ManagerSetUserVacation.as_view(), name='manager_set_user_vacation'),

    url(r'^export_user_vacations/$', export_user_vacations, name='export_user_vacations'),

    url(r'^invitation/$', Invitation.as_view(), name='invitation'),

    url(r'^test/$', test),

    url(r'^$', Dashboard.as_view(), name='dashboard'),

    url(r'^oauth2callback/$', oauth2callback, name='oauth2callback'),
    url(r'^logout/$', logout, name='logout'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static('/.well-known/', document_root='/var/www/html/.well-known/')

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

PTO_project_core/forms.py
# -*- coding: utf-8 -*-
from django import forms

from PTO_project_core.helpers import CalendarBuilder as CalendarBuilderFile
from PTO_project_core.helpers.PtoVacationValidationHelper import PtoVacationValidationHelper
from PTO_project_core.models import PTOUser, PTORole, PTOUserStatus, VacationType


class VacationForm(forms.Form):
    start_date = forms.DateTimeField(widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall js-start-date', 'autocomplete': 'off'}))
    end_date = forms.DateTimeField(widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall', 'autocomplete': 'off'}))
    start_time = forms.FloatField(widget=forms.HiddenInput(), initial=CalendarBuilderFile.START_WORKING_HOUR)
    end_time = forms.FloatField(widget=forms.HiddenInput(), initial=CalendarBuilderFile.END_WORKING_HOUR)
    vacation_type = forms.IntegerField(required=True, widget=forms.Select(
        # comment VacationType here, if "migrate" calls at first time =/
        choices=VacationType.get_vacation_type_choices(),
        attrs={'class': 'form-control select-vacation form-control--tall js-select-type'}
    ))
    comment = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-control--tall', 'placeholder': 'your current projects'}
    ))
    pto_user_id = forms.IntegerField(widget=forms.HiddenInput())

    def is_valid(self):
        valid = super(VacationForm, self).is_valid()
        if not valid:
            return valid

        pto_user_id_ = self.cleaned_data['pto_user_id']
        pto_user_ = PTOUser.objects.get(id=pto_user_id_)
        v_type = VacationType.objects.get(id=self.cleaned_data['vacation_type'])

        pto_vacation_validation_helper = PtoVacationValidationHelper(form=self, user=pto_user_,
                                                                     start_date=self.cleaned_data['start_date'],
                                                                     end_date=self.cleaned_data['end_date'])

        return \
            pto_vacation_validation_helper.base_validate and \
            pto_vacation_validation_helper.not_paid_validate(v_type) and \
            pto_vacation_validation_helper.work_from_home_validate(v_type) and \
            pto_vacation_validation_helper.pto_validate(v_type) and \
            pto_vacation_validation_helper.previous_year_pto_validate(v_type) and \
            pto_vacation_validation_helper.intersection_validate()


class PTOUserForm(forms.Form):
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'js-native-upload native-upload'}), required=False)
    position = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control--tall'}))
    employment_start_datetime = forms.DateField(widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall', 'autocomplete': 'off'}
    ))
    pto_user_manager = forms.IntegerField(required=False, widget=forms.Select(
        attrs={'class': 'form-control form-control--tall'}
    ))
    pto_role = forms.IntegerField(required=False, widget=forms.Select(
        choices=PTORole.objects.all().values_list('id', 'name'),
        attrs={'class': 'form-control form-control--tall js-select'}
    ))
    pto_user_status = forms.IntegerField(required=False, widget=forms.Select(
        choices=PTOUserStatus.objects.all().values_list('id', 'name'),
        attrs={'class': 'form-control form-control--tall js-select'}
    ))


class SetUserVacationForm(forms.Form):
    start_date = forms.DateTimeField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall js-start-date', 'autocomplete': 'off', 'required': 'true'}))
    end_date = forms.DateTimeField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall', 'autocomplete': 'off', 'required': 'true'}))
    vacation_type = forms.IntegerField(required=True, widget=forms.Select(
        # comment VacationType here, if "migrate" calls at first time =/
        choices=VacationType.objects.values_list('id', 'name'),
        attrs={'class': 'form-control select-vacation form-control--tall js-select-type'}
    ))
    pto_user_id = forms.IntegerField(widget=forms.HiddenInput())
    comment = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-control--tall'}
    ))

    def is_valid(self):
        valid = super(SetUserVacationForm, self).is_valid()

        if not valid:
            return valid

        v_type = VacationType.objects.get(id=self.cleaned_data['vacation_type'])
        pto_user_id_ = self.cleaned_data['pto_user_id']
        pto_user_ = PTOUser.objects.get(id=pto_user_id_)

        pto_vacation_validation_helper = PtoVacationValidationHelper(form=self, user=pto_user_,
                                                                     start_date=self.cleaned_data['start_date'],
                                                                     end_date=self.cleaned_data['end_date'])

        return \
            pto_vacation_validation_helper.base_validate and \
            pto_vacation_validation_helper.intersection_validate()


class ManagerSetUserVacationForm(forms.Form):
    start_date = forms.DateTimeField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall js-start-date', 'autocomplete': 'off', 'required': 'true'}))
    end_date = forms.DateTimeField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control form-control--tall', 'autocomplete': 'off', 'required': 'true'}))
    vacation_type = forms.IntegerField(required=True, widget=forms.Select(
        choices=VacationType.objects.filter(can_be_used_by_manager=True).values_list('id', 'name'),
        attrs={'class': 'form-control select-vacation form-control--tall js-select-type'}
    ))
    pto_user_id = forms.IntegerField(widget=forms.HiddenInput())
    comment = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-control--tall'}
    ))

    def is_valid(self):
        valid = super(ManagerSetUserVacationForm, self).is_valid()

        if not valid:
            return valid

        pto_user_id_ = self.cleaned_data['pto_user_id']
        pto_user_ = PTOUser.objects.get(id=pto_user_id_)
        v_type = VacationType.objects.get(id=self.cleaned_data['vacation_type'])

        pto_vacation_validation_helper = PtoVacationValidationHelper(form=self, user=pto_user_,
                                                                     start_date=self.cleaned_data['start_date'],
                                                                     end_date=self.cleaned_data['end_date'])

        return \
            pto_vacation_validation_helper.base_validate and \
            pto_vacation_validation_helper.intersection_validate() and \
            pto_vacation_validation_helper.force_majeure_validate(v_type)

PTO_project/templates/login.html
{% extends 'base/base.html' %}

{% block javascript %}
    {{ block.super }}
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="{{ GOOGLE_CLIENT_ID }}">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
{% endblock %}

{% block content %}
    <div class="container container-general">
        <div class="g-signin2" data-onsuccess="onSignIn" data-redirecturi="{{ success_redirect_url }}" data-theme="dark">
        </div>

        <script>
            function onSignIn(googleUser) {
                // Useful data for your client-side scripts:
                var profile = googleUser.getBasicProfile();
                console.log("ID: " + profile.getId()); // Don't send this directly to your server!
                console.log("Name: " + profile.getName());
                console.log("Image URL: " + profile.getImageUrl());
                console.log("Email: " + profile.getEmail());

                // The ID token you need to pass to your backend:
                var id_token = googleUser.getAuthResponse().id_token;
                console.log("ID Token: " + id_token);

                $.post("/login/", {id_token: id_token, email: profile.getEmail()},
                        function (data) {
                            if (data.message) {
                                $('#error_container').text(data.message).removeClass('hidden');
                            }
                            else {
                                window.location.href = '/dashboard/';
                            }

                        }
                );
            }

        </script>

        <div id="error_container" class="alert alert-danger hidden">


        </div>

        {{ login_error }}
    </div>
{% endblock %}

PTO_project/templates/login_errors.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container container-general">
        {% if pto_login_error %}

            <div class="alert alert-danger">
                {{ pto_login_error }}
            </div>
        {% endif %}
    </div>
{% endblock %}

PTO_project/templates/test.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container container-general">
        <h1>Tests</h1>

        <button id="del_session" class="btn btn-danger">
            Delete PTO session
        </button>



        <script>
            $('#del_session').click(function () {
                $.ajax
                ({
                    url: '/test/',
                    data: {del_pto_session: '1'},
                    type: 'post',
                    success: function (result) {
                        $('#answer').text(result);
                    }
                });
            });
        </script>


        <button class="btn btn-info" onclick="signOut();">Sign out</button>
        <script>
            function signOut() {
                var auth2 = gapi.auth2.getAuthInstance();
                auth2.signOut().then(function () {
                    $('#answer').text('User signed out.');
                });
            }
        </script>


        <hr>

        <div id="answer">

        </div>

        <code>
            {{ request.session.pto_google_auth }}
        </code>
    </div>
{% endblock %}

PTO_project/templates/thank_you_page.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/thank_you_page.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="container container-general">
        <div class="row page__header">
            <div class="col-md-12">
                <div class="page__title">Thank you!</div>
                <div class="page__intro">
                    Your request on period <b>{{ start_date|date:'Y-m-d' }} - {{ end_date|date:'Y-m-d' }}</b> was submitted.<br>
                    You will receive an email notification when your request is approved or denied.
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="section__title">You will be redirected to the PTO management homepage automatically in <span id="js-timer_down">5 seconds</span>...</div>
            </div>
        </div>
    </div>
{% endblock %}

PTO_project/templates/user.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/user.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="container container-general">
        <div class="row page__header">
            <div class="col-md-12">
                <div class="page__title page__title--center">User edit</div>
            </div>
        </div>

        <form enctype="multipart/form-data" method="post">
            <div class="form-container-middle">
                {% if message %}
                    <div class="{{ message.type }}">
                        {{ message.text }}
                    </div>
                {% endif %}

                <div class="form-group">
                    <label for="" class="form-label">User Name</label>
                    <input type="text" value="{{ user.first_name }} {{ user.last_name }}" name="username" id=""
                           class="form-control form-control--tall" readonly="readonly">
                </div>

                {% if is_hr_manager %}
                    <div class="form-group">
                        <label for="" class="form-label">Role</label>
                        {{ form.pto_role }}
                        {{ form.pto_role.errors }}
                    </div>

                    <div class="form-group">
                        <label for="" class="form-label">Status</label>
                        {{ form.pto_user_status }}
                        {{ form.pto_user_status.errors }}
                    </div>

                    <div class="form-group">
                        <label for="" class="form-label">Manager</label>
                        <select class="form-control form-control--tall js-select js-select-manager" id="id_pto_user_manager"
                                name="pto_user_manager">
                            <option value="">No Manager</option>
                            {% for user_manager in managers %}
                                <option value="{{ user_manager.id }}"
                                        {% if user.pto_user_manager_id == user_manager.id %}selected{% endif %}>
                                    {{ user_manager.first_name }} {{ user_manager.last_name }}
                                </option>
                            {% endfor %}
                        </select>
                        {{ form.pto_user_manager.errors }}
                    </div>
                {% endif %}

                <div class="form-group">
                    <label for="" class="form-label">Position</label>
                    {{ form.position }}
                    {{ form.position.errors }}
                </div>

                <div class="form-group">
                    <label for="" class="form-label">Hire Date</label>
                    <div class="date date-picker">
                            <span class="btn btn--big btn-data">
                                <i class="fa fa-calendar icon"></i>
                            </span>
                        <div class="overflow is-empty">
                            {{ form.employment_start_datetime }}
                            {{ form.employment_start_datetime.errors }}
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div id="avatar_container" class="account__photo-container account__photo-container--medium account__photo-container--user-view">
                        {% if user.photo %}
                            <img src="{{ user.photo.url }}"
                                 class="account__photo">
                            {{ user.photo.url }}
                        {% else %}
                            <i class="fa fa-user"></i>
                        {% endif %}
                    </div>
                    <div class="upload-photo-container">
                        <div class="upload-button js-trigger-upload btn btn-back">Upload Photo</div>
                        <div class="upload-text js-text-upload">No file chosen</div>
                        <div class="remove-photo-button js-trigger-remove-photo btn btn-back">Remove Photo</div>
                        <input type="hidden" id="current_user_id" value="{{ user.id }}">

                        {{ form.photo }}
                        {{ form.photo.errors }}
                    </div>
                </div>

            </div>

            <div class="row row--form page-footer">
                <div class="form-container-middle">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <a href="/#table" class="btn btn-back">Cancel</a>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                <button class="btn btn-primary btn-primary--vacation" type="submit"><i
                                        class="fa fa-floppy-o icon"></i> Save Employee
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

PTO_project/templates/vacation.html
{% extends 'base/base.html' %}
{% load staticfiles%}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/vacation_request.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="container container-general">
        <div class="row page__header">
            <div class="col-md-12 col-sm-12">
                <div class="page__title">Vacation Request</div>
                {% if previous_year_days %}
                    <div>You have <strong class="label label-success">{{ previous_year_days }}</strong> available day{% if previous_year_days > 1 %}s{% endif %} from previous year.</div> <br>
                {% endif %}
                {{ user.get_half_year_text|safe }}
                {% if days_left > 0 %}
                    <div>Total left
                        <strong class="label label-success">{{ days_left }}</strong>
                        (from <strong class="label label-success">{{ total_days }}</strong>)
                        day{% if days_left > 1 %}s{% endif %} by the end of year.
                    </div> <br>
                {% else %}
                    <div>You don't have available PTO days by
                        {% if user.is_new_user %}
                            <strong>{{ user.get_current_end_of_period_date|date:'m/d/Y' }}</strong>.
                        {% else %}
                            the end of year.
                        {% endif %}
                    </div> <br>
                {% endif %}
                {% if current_days_left > 0 %}
                    <div>Current
                        <strong class="label label-success">{{ current_days_left }}</strong>
                        day{% if current_days_left > 1 %}s{% endif %} left.
                    </div> <br>
                {% else %}
                    <div>
                        You don't have available PTO days by today.<br>
                        But you can try request vacation for later time.
                    </div> <br>
                {% endif %}
                <div class="page__intro">Select type of leave and period.</div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-6 account">
                <div class="account__photo-container">
                    {% if request.session.pto_google_auth.PTOUser.photo %}
                        <img src="{{ MEDIA_URL }}{{ request.session.pto_google_auth.PTOUser.photo }}" class="account__photo">
                    {% else %}
                        <i class="fa fa-user"></i>
                    {% endif %}
                </div>
                <div class="account__info">
                    <span class="account__name">
                        {{ request.session.pto_google_auth.PTOUser.first_name }}
                        {{ request.session.pto_google_auth.PTOUser.last_name }}
                    </span><br>
                    <span class="account__email">{{ request.session.pto_google_auth.PTOUser.email }}</span>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="text-center period-container">
                    <span class="period">Period</span>
                </div>
            </div>
        </div>
        <form id="vacation_form" method="post" class="form-vacation" action="{% url 'vacation_request' %}">
            <div class="row row--form">
                <div class="col-md-6 col-sm-6 {% if form.vacation_type.errors|length > 0 %} has-error {% endif %}">
                    <label for="{{ form.vacation_type.id_for_label }}">Leave reason</label>
                    {{ form.vacation_type }}
                    {{ form.vacation_type.errors }}
                </div>
                <div class="col-md-3 col-sm-3 {% if form.start_date.errors|length > 0 %} has-error {% endif %}">
                    <label for="{{ form.start_date.id_for_label }}" class="form-label">From</label>
                    <div class='date date-picker js-from-date js-date-picker-container'>
                        <span class="btn btn--big btn-data">
                            <i class="fa fa-calendar icon"></i>
                        </span>
                        <div class="form-group overflow">
                            {{ form.start_date }}
                        </div>
                        {{ form.start_date.errors }}
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 {% if form.end_date.errors|length > 0 %} has-error {% endif %}">
                    <label for="{{ form.end_date.id_for_label }}" class="form-label">To</label>
                    <div class='date date-picker js-end-date js-date-picker-container'>
                        <span class="btn btn--big btn-data">
                            <i class="fa fa-calendar icon"></i>
                        </span>
                        <div class="form-group overflow">
                            {{ form.end_date }}
                        </div>
                    </div>
                    {{ form.end_date.errors }}
                </div>

            </div>

            <div class="row row--form">
                <div class="col-md-6 col-sm-6 {% if form.comment.errors|length > 0 %} has-error {% endif %}">
                    <label for="{{ form.comment.id_for_label }}">Comment</label>
                    {{ form.comment }}
                    {{ form.comment.errors }}
                </div>
            </div>
            {{ form.pto_user_id }}
            {{ form.start_time }}
            {{ form.end_time }}
            <div class="row row--form">
                <div class="col-md-3 col-sm-3">
                    <a href="{% url 'dashboard' %}" class="btn btn-back">Back</a>
                </div>
                <div class="col-md-offset-6 col-sm-offset-6 col-md-3 col-sm-3">
                    <button class="btn btn-primary btn-primary--vacation" type="submit">
                        <i class="fa fa-envelope icon"></i> Submit
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}